#ifndef MPS_CONFIG_H_
#define MPS_CONFIG_H_

#define MPS_CONFIG_STACK_MAX_SIZE 3

#define MPS_CONFIG_USE_PRIOR_RTOS

#define MPS_CONFIG_USE_STD_MALLOC

#define MPS_CONFIG_MEMORY_SIZE_BYTES 500


#endif